# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Colors Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$bg_color = rgba(EBCB8Bff)
$primary_color = rgba(EBCB8Bff)
$cachymgreen = rgba(EBCB8Bff)
$cachydgreen = rgba(EBCB8Bff)
$cachylblue = rgba(EBCB8Bff)
$cachydblue = rgba(EBCB8Bff)
# $cachydblue = rgba(111826ff)
