# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = nautilus
$applauncher = wofi
$terminal = alacritty
$browser = microsoft-edge-stable
$browser_private = microsoft-edge-stable --inprivate 'https://gemini.google.com/'
$idlehandler = hypridle 
$pgpath = 

# Screenshots
$shot-region = grimblast copy area
$shot-window = grimblast copy active
$shot-screen = grimblast copy output
