# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2
    
    kb_layout = us, ara
    kb_options = grp:alt_shift_toggle

	touchpad {
		natural_scroll = true
		middle_button_emulation = true
	}
}

cursor {
    no_warps = true 
    # this will prevent the cursor from going to the center of each window on focus change
}
