# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/Configuring/Monitors/

monitor = , 3072x1920@120, auto, 1.6
# monitor = , preferred, auto, 1.6

# chromium
env = QT_QPA_PLATFORMTHEME,qt5ct,wayland #added wayland
env = GDK_BACKEND,wayland,x11 #added x11
env = OZONE_PLATFORM_HINT,auto

# If you need to scale things like steam etc, please uncomment these lines.
xwayland {
  force_zero_scaling = true       # Unscale XWayland
}

# Adjust GDK_SCALE accordingly to your liking.
#env = GDK_SCALE, 2                # GDK Scaling Factor (no fractional scaling)

# Electron based apps use X11 as default, auto should detect wayland
env = ELECTRON_OZONE_PLATFORM_HINT, auto
